export const fontFamily = [
  { name: 'Roboto', value: 'Roboto' },
  { name: 'Open Sans', value: 'Open Sans' },
  { name: 'Lato', value: 'Lato' },
  { name: 'Montserrat', value: 'Montserrat' },
  { name: 'Poppins', value: 'Poppins' },
  { name: 'Oswald', value: 'Oswald' },
  { name: 'Source Sans 3', value: 'Source Sans 3' },
  { name: 'Inter', value: 'Inter' },
  { name: 'Raleway', value: 'Raleway' },
  { name: 'Merriweather', value: 'Merriweather' },
  { name: 'Playfair Display', value: 'Playfair Display' },
  { name: 'Ubuntu', value: 'Ubuntu' },
  { name: 'Nunito', value: 'Nunito' },
  { name: 'PT Serif', value: 'PT Serif' },
  { name: 'Bebas Neue', value: 'Bebas Neue' },
  { name: 'Barlow', value: 'Barlow' },
  { name: 'Manrope', value: 'Manrope' },
  { name: 'Fira Sans', value: 'Fira Sans' },
  { name: 'Noto Sans', value: 'Noto Sans' },
  { name: 'DM Sans', value: 'DM Sans' },
  { name: 'Kanit', value: 'Kanit' },
  { name: 'Quicksand', value: 'Quicksand' },
  { name: 'Varela Round', value: 'Varela Round' },
  { name: 'Libre Baskerville', value: 'Libre Baskerville' },
  { name: 'Cabin', value: 'Cabin' }
];

export const fontWeights = [
  { name: 'Thin', value: 100 },
  { name: 'ExtraLight', value: 200 },
  { name: 'Light', value: 300 },
  { name: 'Regular', value: 400 },
  { name: 'Medium', value: 500 },
  { name: 'SemiBold', value: 600 },
  { name: 'Bold', value: 700 },
  { name: 'ExtraBold', value: 800 },
  { name: 'Black', value: 900 }
];

export const fontSizes = [
  { name: '8', value: 8 },
  { name: '10', value: 10 },
  { name: '12', value: 12 },
  { name: '14', value: 14 },
  { name: '16', value: 16 },
  { name: '18', value: 18 },
  { name: '20', value: 20 },
  { name: '22', value: 22 },
  { name: '24', value: 24 },
  { name: '26', value: 26 },
  { name: '28', value: 28 },
  { name: '30', value: 30 },
  { name: '32', value: 32 },
  { name: '34', value: 34 },
  { name: '36', value: 36 },
  { name: '38', value: 38 },
  { name: '40', value: 40 },
  { name: '42', value: 42 },
  { name: '44', value: 44 },
  { name: '46', value: 46 },
  { name: '48', value: 48 },
  { name: '50', value: 50 },
  { name: '52', value: 52 },
  { name: '54', value: 54 },
  { name: '56', value: 56 },
  { name: '58', value: 58 },
  { name: '60', value: 60 },
  { name: '62', value: 62 },
  { name: '64', value: 64 },
  { name: '66', value: 66 },
  { name: '68', value: 68 },
  { name: '70', value: 70 },
  { name: '72', value: 72 },
  { name: '74', value: 74 },
  { name: '76', value: 76 },
  { name: '78', value: 78 },
  { name: '80', value: 80 },
  { name: '82', value: 82 },
  { name: '84', value: 84 },
  { name: '86', value: 86 },
  { name: '88', value: 88 },
  { name: '90', value: 90 },
  { name: '92', value: 92 },
  { name: '94', value: 94 },
  { name: '96', value: 96 }
];
