export const fontFamily = [
  { name: 'Roboto', value: 'Roboto, Arial, sans-serif' },
  { name: 'Open Sans', value: 'Open Sans, Arial, sans-serif' },
  { name: 'Lato', value: 'Lato, Arial, sans-serif' },
  { name: 'Montserrat', value: 'Montserrat, Arial, sans-serif' },
  { name: 'Poppins', value: 'Poppins, Arial, sans-serif' },
  { name: 'Oswald', value: 'Oswald, Arial, sans-serif' },
  { name: 'Source Sans Pro', value: 'Source Sans Pro, Arial, sans-serif' },
  { name: 'Inter', value: 'Inter, Arial, sans-serif' },
  { name: 'Raleway', value: 'Raleway, Arial, sans-serif' },
  { name: 'Merriweather', value: 'Merriweather, Georgia, serif' },
  { name: 'Playfair Display', value: 'Playfair Display, Georgia, serif' },
  { name: 'Ubuntu', value: 'Ubuntu, Arial, sans-serif' },
  { name: 'Nunito', value: 'Nunito, Arial, sans-serif' },
  { name: 'PT Serif', value: 'PT Serif, Georgia, serif' },
  { name: 'Bebas Neue', value: 'Bebas Neue, Arial, sans-serif' },
  { name: 'Barlow', value: 'Barlow, Arial, sans-serif' },
  { name: 'Manrope', value: 'Manrope, Arial, sans-serif' },
  { name: 'Fira Sans', value: 'Fira Sans, Arial, sans-serif' },
  { name: 'Noto Sans', value: 'Noto Sans, Arial, sans-serif' },
  { name: 'DM Sans', value: 'DM Sans, Arial, sans-serif' },
  { name: 'Kanit', value: 'Kanit, Arial, sans-serif' },
  { name: 'Quicksand', value: 'Quicksand, Arial, sans-serif' },
  { name: 'Varela Round', value: 'Varela Round, Arial, sans-serif' },
  { name: 'Libre Baskerville', value: 'Libre Baskerville, Georgia, serif' },
  { name: 'Cabin', value: 'Cabin, Arial, sans-serif' }
];

export const fontWeights = [
  { name: 'Thin', value: 100 },
  { name: 'ExtraLight', value: 200 },
  { name: 'Light', value: 300 },
  { name: 'Regular', value: 400 },
  { name: 'Medium', value: 500 },
  { name: 'SemiBold', value: 600 },
  { name: 'Bold', value: 700 },
  { name: 'ExtraBold', value: 800 },
  { name: 'Black', value: 900 }
];

export const fontSizes = [
  { name: '8', value: 8 },
  { name: '10', value: 10 },
  { name: '12', value: 12 },
  { name: '14', value: 14 },
  { name: '16', value: 16 },
  { name: '18', value: 18 },
  { name: '20', value: 20 },
  { name: '24', value: 24 },
  { name: '28', value: 28 },
  { name: '32', value: 32 },
  { name: '36', value: 36 },
  { name: '40', value: 40 },
  { name: '48', value: 48 },
  { name: '56', value: 56 },
  { name: '64', value: 64 },
  { name: '72', value: 72 },
  { name: '80', value: 80 },
  { name: '96', value: 96 }
];
